export const USER_SENT_MESSAGE = 'USER_SENT_MESSAGE';
export const CLIENT_SENT_MESSAGE = 'CLIENT_SENT_MESSAGE';
export const RESET_CHAT_MESSAGES = 'RESET_CHAT_MESSAGES';
export const GET_INITIAL_DATA_PENDING = 'GET_INITIAL_DATA_PENDING';
export const GET_INITIAL_DATA_SUCCESS = 'GET_INITIAL_DATA_SUCCESS';
export const GET_INITIAL_DATA_FAILURE = 'GET_INITIAL_DATA_FAILURE';