export const GET_INITIAL_DATA_PENDING = 'GET_INITIAL_DATA_PENDING';
export const GET_INITIAL_DATA_SUCCESS = 'GET_INITIAL_DATA_SUCCESS';
export const GET_INITIAL_DATA_FAILURE = 'GET_INITIAL_DATA_FAILURE';